version: "3"
services:
  estoque:
    build: .
    container_name: estoque
    network_mode: bridge
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:12.1
    container_name: postgres
    network_mode: bridge
    expose:
      - 5432
    environment:
      - POSTGRES_DB=estoquepulse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql